### ISSUE TITLE
Script getUserId retourne pas le id pour un certain compte

### ISSUE THREAD

**Issue by gaetan1903** [iTeam-S/Bot-Crush#2]
Quand le compte facebook est verrouilé, 

il n y a le r.php? dans le code , il faudrait peut etre jouer sur le `rid` je pense 

Merci de ton action

**Comment by rootkit7628** [comment]
ok je m'en occupe dans un instant @gaetan1903

**Comment by rootkit7628** [comment]
05d3269

**Comment by rivo2302** [comment]
@rootkit7628 l'erreur est encore là

**Comment by rivo2302** [comment]
Voici ceux qui bug:   liantsoa.Mel,Dominick.Cekah

**Comment by rootkit7628** [comment]
@rivo2302 c'est juste sur les cookies le problème mais j'ai déjà réglé le problème ici 2c428a2 mais n'oublie pas d'entrer tes identifiants de connexion soit par varibles d'environnement soit tu complete directement sur le code 
![image](https://user-images.githubusercontent.com/60097202/105318630-cae2fd00-5bd4-11eb-848c-5c8c603c27a5.png)
