### ISSUE TITLE
Optimiser le  travail du navigateur

### ISSUE THREAD

**Issue by rivo2302** [iTeam-S/Bot-Crush#3]
Les envoie de message ,effacer la discussio  , tout se qui touche selenium seront stockées dans une table de la base de donée . Le navigateur ne se ferme plus mais attend qu'il y du mouvement dans cette table et fait le boulot.

**Comment by gaetan1903** [comment]
Faut deja commencer par le schema de la table

**Comment by gaetan1903** [comment]
75b11b7d90b9988983738b29f183da231e2d70d1 🥇

**Comment by gaetan1903** [comment]
C'est fonctionnel avec le dernier commit que j'ai mis en commentaire
